/**
 * @fileoverview Formato de visualización y configuración pública de estados financieros para frontend y reportes.
 * @module services/edgar/statementDisplay
 */

import { CONCEPTS } from './statementConcepts.js';

export const DISPLAY_STATEMENTS = {
  valuation: [
    { kind: 'section', label: 'Múltiplos de valoración' },
    { key: 'evToEbitda', label: 'EV / EBITDA', format: 'multiple', emphasis: true },
    { key: 'peRatio', label: 'PER', format: 'multiple', emphasis: true },
    { key: 'priceToFcf', label: 'P / FCF', format: 'multiple', emphasis: true },
    { key: 'dividendYield', label: 'Yield del dividendo %', format: 'ratio', emphasis: true },
    { key: 'payoutRatio', label: 'Payout del dividendo %', format: 'ratio', emphasis: true },
    { key: 'netDebtToEbitda', label: 'Deuda Neta / EBITDA', format: 'multiple', emphasis: true },
    { kind: 'section', label: 'Desglose y magnitudes de valoración:' },
    { key: 'marketCap', label: 'Capitalización de mercado', format: 'money' },
    { key: 'enterpriseValue', label: 'Enterprise Value (EV)', format: 'money', emphasis: true },
    { key: 'totalDebt', label: 'Deuda total', format: 'money' },
    { key: 'cashAndShortTermInvestments', label: 'Efectivo total e inversiones a corto plazo', format: 'money' },
    { key: 'netDebt', label: 'Deuda neta', format: 'money', emphasis: true },
    { key: 'ebitda', label: 'EBITDA', format: 'money', emphasis: true },
    { key: 'epsDiluted', label: 'Beneficio neto por acción (BPA diluido)', format: 'perShare' },
    { key: 'cashFlowPerShare', label: 'Flujo de caja libre por acción (FCF / acción)', format: 'perShare' },
    { key: 'freeCashFlow', label: 'Flujo de caja libre (FCF)', format: 'money' },
    { key: 'dividendPerShare', label: 'Dividendo por acción', format: 'perShare' },
  ],
  income: [
    { kind: 'section', label: 'Ingresos' },
    { key: 'revenue', label: 'Ingresos totales', emphasis: true },
    { key: 'revenueGrowth', kind: 'change', baseKey: 'revenue', label: '% De cambio interanual', format: 'percent' },
    { key: 'costOfRevenue', label: 'Coste de los bienes vendidos', tone: 'negative' },
    { key: 'grossProfit', label: 'Beneficio bruto', emphasis: true },
    { key: 'grossProfitGrowth', kind: 'change', baseKey: 'grossProfit', label: '% De cambio interanual', format: 'percent' },
    { key: 'grossProfitMargin', kind: 'margin', baseKey: 'grossProfit', label: '% Márgenes brutos', format: 'percent' },
    { key: 'sellingGeneralAdmin', label: 'Gastos de venta generales y administrativos', tone: 'negative' },
    { key: 'researchDevelopment', label: 'Gastos de I+D', tone: 'negative' },
    { key: 'amortizationGoodwillIntangibles', label: 'Amortización de fondos de comercio y activos intangibles', tone: 'negative' },
    { key: 'otherOperatingExpenses', label: 'Otros gastos operacionales', tone: 'negative' },
    { key: 'operatingExpenses', label: 'Gastos operativos totales', tone: 'negative', emphasis: true },
    { key: 'operatingIncome', label: 'Beneficio operativo', emphasis: true },
    { key: 'operatingIncomeGrowth', kind: 'change', baseKey: 'operatingIncome', label: '% De cambio interanual', format: 'percent' },
    { key: 'operatingIncomeMargin', kind: 'margin', baseKey: 'operatingIncome', label: '% Márgenes operativos', format: 'percent' },
    { key: 'operatingIncomeAdjusted', label: 'Beneficio operativo ajustado', emphasis: true },
    { key: 'operatingIncomeAdjustedMargin', kind: 'margin', baseKey: 'operatingIncomeAdjusted', numeratorKey: 'operatingIncomeAdjusted', denominatorKey: 'revenue', label: 'Margen operativo ajustado %', format: 'percent', italic: true },
    { key: 'interestExpense', label: 'Gastos por intereses', tone: 'negative' },
    { key: 'interestIncome', label: 'Ingresos por intereses e inversiones' },
    { key: 'equityMethodIncome', label: 'Ingresos (pérdidas) sobre capital invertido.' },
    { key: 'foreignCurrencyGainLoss', label: 'Ganancias (pérdidas) cambiarias' },
    { key: 'otherNonoperatingIncome', label: 'Ingresos (gastos) no operativos' },
    { key: 'pretaxIncome', label: 'EBT excl. Artículos inusuales', emphasis: true },
    { key: 'mergerRestructuringCharges', label: 'Cargos de fusión y reestructuraciones', tone: 'negative' },
    { key: 'goodwillImpairment', label: 'Deterioro del fondo de comercio', tone: 'negative' },
    { key: 'gainLossOnInvestments', label: 'Gain (Loss) On Sale Of Investments' },
    { key: 'gainLossOnAssets', label: 'Ganancia (pérdida) en la venta de activos' },
    { key: 'assetImpairment', label: 'Devaluación de activos', tone: 'negative' },
    { key: 'insuranceSettlements', label: 'Liquidaciones de seguros' },
    { key: 'legalSettlements', label: 'Acuerdos legales', tone: 'negative' },
    { key: 'otherUnusualItems', label: 'Otros artículos inusuales' },
    { key: 'ebtIncludingUnusual', label: 'EBT incl. Artículos extraordinarios', emphasis: true },
    { key: 'incomeTax', label: 'Gastos de impuestos' },
    { key: 'incomeFromContinuingOps', label: 'Beneficios por operaciones continuadas', emphasis: true },
    { key: 'discontinuedOperations', label: 'Beneficios por operaciones discontinuadas' },
    { key: 'netIncome', label: 'Beneficio neto de la empresa', emphasis: true },
    { key: 'minorityInterestIncome', label: 'Intereses minoritario' },
    { key: 'preferredDividendsOtherAdjustments', label: 'Dividendo preferente y otros ajustes', tone: 'negative' },
    { key: 'netIncomeToCommonIncludingUnusual', label: 'Beneficio neto a acciones comunes', emphasis: true },
    { key: 'netIncomeMargin', kind: 'margin', baseKey: 'netIncomeToCommonIncludingUnusual', numeratorKey: 'netIncomeToCommonIncludingUnusual', denominatorKey: 'revenue', label: 'Margen de beneficio neto %', format: 'percent', italic: true },
    { key: 'netIncomeToCommonExcludingUnusual', label: 'Beneficio neto ajustado', emphasis: true },
    { key: 'netIncomeAdjustedMargin', kind: 'margin', baseKey: 'netIncomeToCommonExcludingUnusual', numeratorKey: 'netIncomeToCommonExcludingUnusual', denominatorKey: 'revenue', label: 'Margen de beneficio neto ajustado %', format: 'percent', italic: true },
    { kind: 'section', label: 'Datos adicionales:' },
    { key: 'epsDiluted', label: 'BPA diluido', format: 'perShare' },
    { key: 'epsDilutedGrowth', kind: 'change', baseKey: 'epsDiluted', label: '% De cambio interanual', format: 'percent' },
    { key: 'epsDilutedNormalized', label: 'BPA diluido ajustado', format: 'perShare' },
    { key: 'epsDilutedNormalizedGrowth', kind: 'change', baseKey: 'epsDilutedNormalized', label: '% De cambio interanual', format: 'percent' },
    { key: 'weightedSharesDiluted', label: 'Promedio ponderado de acciones diluidas en circulación', format: 'shares' },
    { key: 'weightedSharesDilutedGrowth', kind: 'change', baseKey: 'weightedSharesDiluted', label: '% De cambio interanual', format: 'percent' },
    { key: 'weightedSharesBasic', label: 'Promedio ponderado de acciones básicas en circulación', format: 'shares' },
    { key: 'weightedSharesBasicGrowth', kind: 'change', baseKey: 'weightedSharesBasic', label: '% De cambio interanual', format: 'percent' },
    { key: 'dividendPerShare', label: 'Dividendo por acción', format: 'perShare' },
    { key: 'dividendPerShareGrowth', kind: 'change', baseKey: 'dividendPerShare', label: '% De cambio interanual', format: 'percent' },
    { key: 'dividendPayoutDiluted', kind: 'ratio', numeratorKey: 'dividendPerShare', denominatorKey: 'epsDiluted', label: 'Dividendo pagado sobre el beneficio neto %', format: 'percent' },
    { key: 'dividendPayoutNormalized', kind: 'ratio', numeratorKey: 'dividendPerShare', denominatorKey: 'epsDilutedNormalized', label: 'Dividendo pagado sobre el beneficio neto ajustado %', format: 'percent' },
    { key: 'epsBasic', label: 'BPA básico', format: 'perShare' },
    { key: 'ebitda', label: 'EBITDA' },
    { key: 'ebitdaGrowth', kind: 'change', baseKey: 'ebitda', label: '% De cambio interanual', format: 'percent' },
    { key: 'ebitdaMargin', kind: 'margin', baseKey: 'ebitda', label: '% Márgenes EBITDA', format: 'percent', italic: true },
    { key: 'ebitdar', label: 'EBITDAR' },
    { key: 'researchDevelopment', label: 'Gasto en I+D' },
    { key: 'salesMarketing', label: 'Gastos de venta y marketing', tone: 'negative' },
    { key: 'effectiveTaxRate', kind: 'ratio', numeratorKey: 'incomeTax', denominatorKey: 'pretaxIncome', absoluteNumerator: true, label: 'Tasa efectiva de impuestos %', format: 'percent' },
  ],
  balance: [
    { key: 'cash', label: 'Efectivo y equivalentes' },
    { key: 'shortTermInvestments', label: 'Activos financieros para vender' },
    { key: 'cashAndShortTermInvestments', label: 'Efectivo total e inversiones a corto plazo', emphasis: true },
    { key: 'receivables', label: 'Cuentas por cobrar' },
    { key: 'otherReceivables', label: 'Otros por cobrar' },
    { key: 'totalReceivables', label: 'Total de cuentas por cobrar', emphasis: true },
    { key: 'inventory', label: 'Inventario' },
    { key: 'prepaidExpenses', label: 'Gastos pagados por anticipado' },
    { key: 'deferredTaxAssetsCurrent', label: 'Activos por impuestos diferidos Corrientes' },
    { key: 'otherCurrentAssets', label: 'Otro activo corriente' },
    { key: 'currentAssets', label: 'Total de activo corriente', emphasis: true },
    { key: 'propertyPlantEquipmentGross', label: 'Inmovilizado material bruto' },
    { key: 'accumulatedDepreciation', label: 'Depreciación acumulada', tone: 'negative' },
    { key: 'propertyPlantEquipment', label: 'Inmovilizado material neto', emphasis: true },
    { key: 'longTermInvestments', label: 'Inversiones a largo plazo' },
    { key: 'goodwill', label: 'Fondo de comercio' },
    { key: 'otherIntangibleAssets', label: 'Otros intangibles' },
    { key: 'longTermReceivables', label: 'Préstamos por cobrar a largo plazo' },
    { key: 'deferredTaxAssetsNoncurrent', label: 'Activos por impuestos diferidos a largo plazo' },
    { key: 'deferredCharges', label: 'Cargos diferidos a largo plazo' },
    { key: 'otherAssetsNoncurrent', label: 'Otros activos a largo plazo' },
    { key: 'assets', label: 'Activo total', emphasis: true },
    { key: 'payables', label: 'Cuentas por pagar' },
    { key: 'accruedLiabilities', label: 'Gastos devengados' },
    { key: 'shortTermLoans', label: 'Préstamos de corto plazo' },
    { key: 'longTermDebtCurrent', label: 'Porción corriente de la deuda a largo plazo' },
    { key: 'currentCapitalLeaseObligations', label: 'Porción corriente de las obligaciones de arrendamiento financiero' },
    { key: 'deferredTaxLiabilitiesCurrent', label: 'Pasivo por impuestos diferidos Corriente' },
    { key: 'otherCurrentLiabilities', label: 'Otros pasivos corrientes' },
    { key: 'currentLiabilities', label: 'Total pasivo corriente', emphasis: true },
    { key: 'longTermDebt', label: 'Deuda a largo plazo' },
    { key: 'capitalLeasesNoncurrent', label: 'Arrendamientos de capitales' },
    { key: 'pensions', label: 'Pensiones y otros beneficios posteriores a la jubilación' },
    { key: 'deferredTaxLiabilitiesNoncurrent', label: 'Pasivo por impuesto diferido no corriente' },
    { key: 'otherLiabilitiesNoncurrent', label: 'Otro pasivo no corriente' },
    { key: 'liabilities', label: 'Pasivo Total', emphasis: true },
    { key: 'commonStock', label: 'Acciones comunes' },
    { key: 'additionalPaidInCapital', label: 'Prima de suscripción' },
    { key: 'retainedEarnings', label: 'Beneficio no distribuido' },
    { key: 'treasuryStock', label: 'Autocartera', tone: 'negative' },
    { key: 'accumulatedOtherComprehensiveIncome', label: 'Resultado integral y otros' },
    { key: 'commonEquity', label: 'Patrimonio neto común total', emphasis: true },
    { key: 'minorityInterest', label: 'Intereses minoritarios' },
    { key: 'equity', label: 'Fondos propios totales', emphasis: true },
    { key: 'liabilitiesAndEquity', label: 'Pasivo total y patrimonio neto', emphasis: true },
    { kind: 'section', label: 'Datos adicionales:' },
    { key: 'sharesOutstanding', label: 'Total de acciones fuera en la fecha de presentación', format: 'shares' },
    { key: 'bookValuePerShare', label: 'Valor contable / Acción', format: 'perShare' },
    { key: 'tangibleBookValue', label: 'Valor contable tangible' },
    { key: 'tangibleBookValuePerShare', label: 'Tangible Book Value / Share', format: 'perShare' },
    { key: 'totalDebt', label: 'Deuda total' },
    { key: 'netDebt', label: 'Deuda neta' },
    { key: 'minorityInterest', label: 'Interés minoritario total' },
    { key: 'equityMethodInvestments', label: 'Inversiones por método de participación' },
    { key: 'land', label: 'Terrenos' },
    { key: 'buildings', label: 'Edificios' },
    { key: 'constructionInProgress', label: 'Construcción en progreso' },
    { key: 'employees', label: 'Empleados a tiempo completo', format: 'count' },
  ],
  cashflow: [
    { key: 'netIncome', label: 'Beneficio netos' },
    { key: 'depreciation', label: 'Depreciación y amortización' },
    { key: 'cashflowAmortizationGoodwillIntangibles', label: 'Amortización de fondos de comercio y activos intangibles' },
    { key: 'depreciationAmortizationTotal', label: 'Depreciación y amortización total' },
    { key: 'amortizationDeferredCharges', label: 'Amortización de cargos diferidos' },
    { key: 'cashflowGainLossOnAssets', label: '(Ganancia) Pérdida por venta de activos' },
    { key: 'cashflowGainLossOnInvestments', label: '(Ganancia) Pérdida por venta de inversiones' },
    { key: 'impairmentRestructuring', label: 'Deterioro de activos y costes de reestructuración' },
    { key: 'equityMethodCashflow', label: '(Ingresos) Pérdidas en inversiones de capital' },
    { key: 'stockCompensation', label: 'Compensación de stock options' },
    { key: 'excessTaxBenefitStockOptions', label: 'Beneficio fiscal de las opciones sobre acciones' },
    { key: 'discontinuedOperationsCFO', label: 'Efectivo neto de operaciones discontinuadas' },
    { key: 'otherOperatingActivities', label: 'Otras actividades operativas' },
    { key: 'changeAccountsReceivable', label: 'Cambio en cuentas por cobrar' },
    { key: 'changeInventory', label: 'Cambio en inventarios' },
    { key: 'changeAccountsPayable', label: 'Cambio en cuentas por pagar' },
    { key: 'changeOtherOperatingAssets', label: 'Variación en otros activos operativos netos' },
    { key: 'cfo', label: 'Efectivo de Operaciones', emphasis: true },
    { key: 'workingCapitalChange', label: 'Nota: Cambio en el capital circulante', italic: true },
    { key: 'capex', label: 'Gastos de capital', tone: 'negative' },
    { key: 'salePPE', label: 'Venta de inmovilizado material' },
    { key: 'acquisitions', label: 'Adquisiciones con efectivo', tone: 'negative' },
    { key: 'divestitures', label: 'Desinversiones' },
    { key: 'securitiesInvesting', label: 'Inversión en valores negociables y de renta variable', tone: 'negative' },
    { key: 'loansInvesting', label: 'Disminución (aumento) neta de préstamos originados / vendidos - Inversión' },
    { key: 'otherInvestingActivities', label: 'Otras actividades de inversión' },
    { key: 'cfi', label: 'Efectivo de la inversión', emphasis: true },
    { key: 'debtIssued', label: 'Deuda total emitida' },
    { key: 'debtPaid', label: 'Total de la deuda reembolsada', tone: 'negative' },
    { key: 'commonStockIssued', label: 'Emisión de acciones ordinarias' },
    { key: 'buybacks', label: 'Recompra de acciones comunes', tone: 'negative' },
    { key: 'dividendsCommon', label: 'Dividendos comunes pagados', tone: 'negative' },
    { key: 'dividendsPreferred', label: 'Dividendos de acciones comunes y preferentes pagados', tone: 'negative' },
    { key: 'otherFinancingActivities', label: 'Otras Actividades de Financiamiento' },
    { key: 'cff', label: 'Efectivo de Financiamiento', emphasis: true },
    { key: 'fx', label: 'Ajustes del tipo de cambio de divisas' },
    { key: 'netChangeInCash', label: 'Cambio neto en efectivo', emphasis: true },
    { kind: 'section', label: 'Datos adicionales:' },
    { key: 'freeCashFlow', label: 'Flujo de caja libre', emphasis: true },
    { key: 'freeCashFlowGrowth', kind: 'change', baseKey: 'freeCashFlow', label: '% De cambio interanual', format: 'percent' },
    { key: 'fcfMargin', kind: 'ratio', numeratorKey: 'freeCashFlow', denominatorKey: 'revenue', label: '% Free Cash Flow Margins', format: 'percent', italic: true },
    { key: 'cashBeginning', label: 'Efectivo y equivalentes de efectivo, comienzo del período' },
    { key: 'cashEnding', label: 'Efectivo y equivalentes de efectivo, fin del período' },
    { key: 'interestPaid', label: 'Intereses en efectivo pagados' },
    { key: 'taxesPaid', label: 'Impuestos en efectivo pagados' },
    { key: 'cashFlowPerShare', label: 'Flujo de caja por acción', format: 'perShare' },
  ],
};

/**
 * Retorna la definición completa de estados contables para consumo de la API pública.
 * @returns {Record<string, Array<object>>} Mapeo de estados financieros y sus partidas.
 */
export function publicStatements() {
  const conceptByKey = new Map(CONCEPTS.map((item) => [item.key, item]));
  return Object.fromEntries(
    Object.entries(DISPLAY_STATEMENTS).map(([statement, items]) => [
      statement,
      items.map((item, index) => {
        const isPercent = item.format === 'percent' || item.kind === 'margin' || item.kind === 'change' || item.kind === 'ratio';
        const fallbackKey = item.kind === 'margin'
          ? `${item.baseKey}Margin`
          : item.kind === 'change'
            ? `${item.baseKey}Growth`
            : item.kind === 'ratio'
              ? `${item.numeratorKey}To${item.denominatorKey.charAt(0).toUpperCase() + item.denominatorKey.slice(1)}Ratio`
              : (item.kind !== 'section' && item.kind !== 'note' ? `${statement}_item_${index}` : undefined);
        const key = item.key ?? fallbackKey;
        return {
          ...item,
          ...(key ? { key } : {}),
          format: item.format ?? (isPercent ? 'percent' : (conceptByKey.get(key)?.format ?? 'money')),
          emphasis: item.emphasis === true,
        };
      }),
    ]),
  );
}
